import {useState} from 'react';
import {ChevronDown,ArrowUpRight} from 'lucide-react';
import './propr-pulse.css';
const outcomes={paid:{label:'All paid',rate:'16.24',passed:4094,failed:21123,active:4681},one:{label:'1-Step',rate:'16.85',passed:1649,failed:8136,active:2365},two:{label:'2-Step',rate:'15.81',passed:2306,failed:12278,active:1765}};
const number=n=>n.toLocaleString('en-US');
export default function ProprPulse(){
 const [open,setOpen]=useState(false),[tab,setTab]=useState('speed'),[program,setProgram]=useState('paid');
 const o=outcomes[program],total=o.passed+o.failed+o.active;
 return <section className={'pp'+(open?' pp-open':'')} aria-label="Propr Pulse">
  <button className="pp-toggle" aria-expanded={open} aria-controls="pp-body" onClick={()=>setOpen(!open)}><span className="pp-name"><strong>propr<span>pulse</span><i>.</i></strong><small>BEYOND THE WALLET</small></span><span className="pp-preview"><b>$2.24M <small>paid</small></b><span>18m median payout · last 7 days</span></span><ChevronDown size={17}/></button>
  <div className="pp-collapse" id="pp-body" inert={open?undefined:''} aria-hidden={!open}><div><div className="pp-inner">
   <div className="pp-tabs" role="group" aria-label="Pulse metric">{[['speed','Payout speed'],['pass','Pass rates'],['milestones','Milestones']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
   <div className="pp-view" aria-live="polite">
   {tab==='speed'&&<><div className="pp-headline"><span>FROM REQUEST TO PAID</span><strong>18m <em>3s</em></strong><p>Median payout time · last 7 days</p></div><div className="pp-speed"><div><b>692</b><span>payouts in the sample</span></div><div><b>2h 8m</b><span>average payout time</span></div><p>The median captures the typical wait; the average includes longer requests. Timing reported by Propr.</p></div></>}
   {tab==='pass'&&<><div className="pp-headline"><span>ASSESSMENT OUTCOMES</span><strong>{o.rate}<em>%</em></strong><p>Passed ÷ resolved assessments</p></div><div className="pp-outcomes"><div className="pp-programs" role="group" aria-label="Assessment type">{Object.entries(outcomes).map(([key,value])=><button key={key} aria-pressed={program===key} onClick={()=>setProgram(key)}>{value.label}</button>)}</div><div className="pp-outcome-bar" aria-hidden="true">{['passed','failed','active'].map(key=><i key={key} className={key} style={{width:`${o[key]/total*100}%`}}/>)}</div><div className="pp-counts">{[['passed','Passed'],['failed','Failed'],['active','Ongoing']].map(([key,label])=><div key={key}><b>{number(o[key])}</b><span>{label}</span></div>)}</div><p>Ongoing assessments are excluded from the pass-rate denominator. Program filters are reported separately by Propr; they are not assumed to sum to All paid.</p></div></>}
   {tab==='milestones'&&<><div className="pp-headline"><span>LIFETIME PAYOUTS</span><strong>$2.24<em>M</em></strong><p>Reported paid to funded traders</p></div><div className="pp-speed"><div><b>1,448</b><span>funded traders paid</span></div><div><b>$30,351</b><span>largest single payout</span></div><p>Lifetime milestones, separate from the rolling wallet-flow totals below.</p></div></>}
   </div>
   {tab==='pass'&&<div className="pp-compare"><div><span className="pp-compare-label">ACROSS LISTED FIRMS</span><h3>More room. A standout pass rate.</h3><p><b>Hypernova Medium: 30.9%</b> — {(30.9/Number(o.rate)).toFixed(2)}× Propr {o.label}’s {o.rate}%, a <b>+{(30.9-Number(o.rate)).toFixed(2)} percentage-point</b> gap.</p></div><div className="pp-compare-bars">{[['Hypernova · Medium',30.9,'nova'],['Hypernova · Low',19.5,'nova'],['Hypernova · Tight',19,'nova'],['Propr · '+o.label,Number(o.rate),'propr']].map(([label,rate,firm])=><div key={label}><span>{label}</span><b>{rate.toFixed(2)}%</b><i style={{width:rate/35*100+'%',background:firm==='nova'?'#b69bcc':'#b5c99d'}}/></div>)}</div><small>Firm-reported snapshots · different programs, trader populations and reporting windows. Historical results; the gap does not establish the effect of the rules. Vest and Breakout: numerical pass rates not found in official sources checked Sep 29, 2026; excluded from this comparison.</small><a href="#novaflow">Explore NovaPulse ↗</a></div>}
   <div className="pp-footer"><p><a href="https://www.propr.xyz/transparency" target="_blank" rel="noopener noreferrer">Source: Propr transparency ↗</a> · Snapshot Sep 29, 2026 (ET)<br/>Reported metrics · not a live feed. Listed payout badges match the sampled ledger by transaction and amount.</p><a className="pp-cta" href="https://app.propr.xyz/r/7gJmpEjv" target="_blank" rel="sponsored noopener noreferrer">Explore Propr <ArrowUpRight size={13}/><small>GIGAPROP referral</small></a></div>
  </div></div></div>
 </section>;
}
