import FirmAtmosphere,{firmMark} from '../design/FirmAtmosphere';
import {ArrowUpRight} from 'lucide-react';
import './vest-hero-offer.css';
export default function SpeedManifesto({about,firms,onOpen}){
  return <section className="review-hero gp-hero-console" id="speed">
    <div className="review-hero-copy"><span className="gp-ghost-type" aria-hidden="true">GP</span><span className="gp-eyebrow">GIGAPROP / WEB3 PROP FIRM REVIEWS</span>
      <h1>Choose the firm.<br/><em>Know the trade-off.</em></h1>
      <p>My shortlist for buying power, trading costs and getting paid. The upside, the catch, and the rules that matter.</p>
      <div className="review-hero-actions"><a className="gp-primary-link" href="#field">Compare the firms <ArrowUpRight size={16}/></a><a className="gp-hero-vest-offer" href="https://next.vestmarkets.com/r/isgigaprop" target="_blank" rel="sponsored noopener noreferrer" aria-label="Open Vest with GIGAPROP’s referral link for 5% off"><img src="/brands/vest-symbol.svg" alt=""/><span><strong>Vest</strong><small>GP referral</small></span><b>5% OFF</b><ArrowUpRight size={15}/></a>{about}</div><nav className="gp-flow-links" aria-label="Onchain flow trackers"><a className="gp-primary-link" href="#flow" style={{background:"#17151d",color:"#c6b8d5",border:"1px solid #b59ac333",fontSize:13,fontWeight:500}}>Flow directory <ArrowUpRight size={13}/></a><a className="gp-primary-link" href="#vestflow" aria-label="Open Vestflow USDC transfer tracker" style={{background:'#151d13',color:'#bac9ad',border:'1px solid #a8c38a26',fontSize:13,fontWeight:500}}>Vestflow</a><a className="gp-primary-link" href="#breakoutflow" aria-label="Open Breakoutflow USDC transfer tracker" style={{background:'#151d13',color:'#bac9ad',border:'1px solid #a8c38a26',fontSize:13,fontWeight:500}}>Breakoutflow</a><a className="gp-primary-link" href="#novaflow" aria-label="Open Novaflow USDC transfer tracker" style={{background:'#151d13',color:'#bac9ad',border:'1px solid #a8c38a26',fontSize:13,fontWeight:500}}>Novaflow</a><a className="gp-primary-link" href="#proprflow" aria-label="Open Proprflow USDC transfer tracker" style={{background:'#151d13',color:'#bac9ad',border:'1px solid #a8c38a26',fontSize:13,fontWeight:500}}>Proprflow</a></nav>
    </div>
    <aside className="gp-firm-editions" aria-label="Explore the shortlist"><div className="gp-editions-heading"><span>THE INDEPENDENT EDIT</span><b>05 / FIRMS</b></div><div className="gp-editions-grid">{firms.map((firm,i)=><button key={firm.id} className={'gp-edition gp-edition-'+firm.id} onClick={()=>onOpen(firm.id)} aria-label={'Explore '+firm.name+' from the overview'}><FirmAtmosphere firm={firm.id}/><span className="gp-edition-index">{String(i+1).padStart(2,'0')}</span><span className="gp-edition-identity"><img src={firmMark(firm.id)||firm.logo} alt=""/><b>{firm.name}</b></span><span className="gp-edition-label">EXPLORE THE FIRM <ArrowUpRight size={12}/></span></button>)}</div><div className="gp-editions-foot"><span>Independent perspective.</span><span>Your next move. In context.</span></div></aside>
  </section>;
}
