import React from "react";
import "./handbook.css";
const concepts=[
 ['01 / Mark the close','Use candle closes to anchor clean horizontal references.','M18 112 L52 82 L82 96 L114 48 L144 66 L172 38 L218 58','M114 48 H224 M144 66 H224',114,48],
 ['02 / Read the structure','See how price moves between levels. Keep the bigger sequence in view.','M18 108 L55 64 L85 84 L122 38 L155 63 L184 48 L218 94','M55 64 H224 M122 38 H224 M85 84 H224',155,63],
 ['03 / Watch the response','At the level: rejection, acceptance, or a change in structure.','M18 110 L55 55 L88 83 L120 48 L145 57 L174 84 L216 113','M55 55 H224 M88 83 H224',145,57]
];
export default function Handbook(){return <div className="tpl-handbook" id="handbook">
<section className="hb-section"><div className="tr-eyebrow">04 / PAYOUT CADENCE</div><h2>Smaller. Sooner.<br/><span>Potentially more useful.</span></h2><div className="hb-cadence"><div><small>ILLUSTRATIVE / ROUTE A</small><strong>$300 <em>at day 2</em></strong><div className="hb-rail"><i style={{left:'9%'}}/></div><p>Cash becomes available earlier. More choice about what comes next.</p></div><div><small>ILLUSTRATIVE / ROUTE B</small><strong>$1,000 <em>at day 21</em></strong><div className="hb-rail purple"><i style={{left:'95%'}}/></div><p>A larger target, with more time and account survival required.</p></div></div><p className="hb-note">Earlier is not automatically better. Compare net cash, likelihood of payout, costs and time together. Day 2 is a hypothetical time to cash, not a claim about a firm's schedule.</p><div className="hb-inline"><b>Scalability is a constraint, too.</b><p>Repeatability matters more than one large target. Account limits, correlated losses, capital tied up and payout rules can stop a small successful cycle from scaling.</p></div></section>
<section className="hb-section hb-denial"><div className="tr-eyebrow">05 / THE FINAL GATE</div><h2>A denial doesn't take a bite.<br/><span>It can end the payout.</span></h2><img src={`${import.meta.env.BASE_URL}mascot/payout-denial.png`} alt="A shadow creature guards a locked gate, stopping a payout before it reaches Wisp."/><div className="hb-inline"><b>I've never had a payout denied.</b><p>That's my experience, and a major reason these firms earn my trust. The receipts support my payout history; they don't guarantee anyone's next request. Eligibility, conduct and clear terms belong in every firm decision.</p></div></section>
<section className="hb-section"><div className="tr-eyebrow">06 / TPL HANDBOOK / MY APPROACH</div><h2>Simple reads.<br/><span>Thousands of chart hours.</span></h2><p>DMC / Dumb Money Concepts is Hunter's concept from Maven Trading. After we spoke in DMs, I realized my own approach was essentially aligned: levels, structure, and reading the response. This is my simplified interpretation.</p><div className="hb-concepts hb-levels">{concepts.map(([title,note,line,level,cx,cy])=><div key={title}><svg viewBox="0 0 240 145" role="img" aria-label={title+' conceptual price path'}><path d={level} fill="none" stroke="#8a2be2" strokeWidth="2"/><path d={line} fill="none" stroke="#d2ff00" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><circle cx={cx} cy={cy} r="13" fill="#d2ff0010" stroke="#d2ff0033"/></svg><h3>{title}</h3><p>{note}</p></div>)}</div><p className="hb-note">Concept sketches, not entry signals or evidence of an edge. Intuition is trained through observation and review; a familiar pattern can still fail.</p></section>
<section className="hb-section"><div className="tr-eyebrow">07 / THE BANKROLL LENS</div><h2>The account is the trade.</h2><p>My lens starts with the cost of an attempt relative to usable drawdown and realistic payout potential. The headline account balance isn't my cash, and drawdown isn't money I can withdraw.</p><div className="hb-economics"><div><small>COST OF AN ATTEMPT</small><strong>My capital at risk</strong><p>Evaluation + activation + subscriptions + any resets I choose.</p></div><span aria-hidden="true">→</span><div><small>USABLE DRAWDOWN</small><strong>Room to execute</strong><p>A rule-defined loss limit, not a guaranteed return.</p></div><span aria-hidden="true">→</span><div><small>NET PAYOUT</small><strong>The actual outcome</strong><p>Cash received, less the costs of all attempts.</p></div></div><div className="hb-inline"><b>The evaluation fee is my starting risk budget.</b><p>It is only the full stop if no further charges are incurred. I cap total spend across attempts. More aggressive account-level risk only makes sense inside that cap, with a tested approach and the firm's rules intact.</p></div><p className="hb-note">A cheap attempt and large drawdown do not create an edge by themselves. Passing, account survival and payout eligibility determine the economics. Scaling the same trade across accounts also scales the same loss.</p><a className="hb-link" href="./#rankings">Find the firms behind my payouts ↗</a><details className="hb-source"><summary>Account rules matter</summary><p>For example, Topstep subscriptions can continue after a failed evaluation, and its prohibited-strategies policy restricts account stacking. Always check the rules for the exact product.</p><a href="https://help.topstep.com/en/articles/8284121-trading-combine-subscriptions" target="_blank" rel="noopener noreferrer">Topstep subscriptions ↗</a><a href="https://help.topstep.com/en/articles/10305426-prohibited-trading-strategies-at-topstep" target="_blank" rel="noopener noreferrer">Prohibited strategies ↗</a></details></section>
</div>}
