import {useMemo,useState} from 'react';
import {Trophy,ChevronDown,ArrowUpRight} from 'lucide-react';
import {payoutLeaderboard} from '../../lib/payout-leaderboard.js';
import './payout-leaders.css';
const money=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2,minimumFractionDigits:2}).format(n);
const short=a=>a.slice(0,6)+'…'+a.slice(-4);
export default function PayoutLeaders({data,config,inline=false}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState(null);
 const sources=config.sources||[config];
 const rows=useMemo(()=>{if(!data)return [];const end=Date.parse(data.windowEnd||data.updatedAt);return data.transfers.filter(t=>Date.parse(t.timestamp)>=end-30*86400000&&Date.parse(t.timestamp)<=end);},[data]);
 const complete=data&&Date.parse(data.periodStart)<=Date.parse(data.windowEnd||data.updatedAt)-30*86400000+60000;
 const leaders=useMemo(()=>complete?payoutLeaderboard(data.transfers,sources,data.windowEnd||data.updatedAt,data.periodStart):[],[rows,config,complete,data]);
 return <section className={'pl'+(inline?' pl-inline':'')}>
 {inline?<header className="pl-heading"><div><Trophy size={14}/><strong>{config.firm}</strong></div><a href={'#'+(config.id==='nova'?'novaflow':config.id+'flow')}>Open tracker <ArrowUpRight size={12}/></a></header>:<button className="pl-trigger" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><Trophy size={14}/><span>Payout Leaders</span><small>TOP 10 / 30D</small><ChevronDown size={14} style={{transform:open?'rotate(180deg)':undefined}}/></button>}
 {(inline||open)&&<div className="pl-body"><div className="pl-caption"><em>the last 30 days</em><span>USDC received</span></div>{leaders.length?<ol>{leaders.map((w,i)=><li key={w.address}><button className="pl-row" aria-expanded={selected===w.address} onClick={()=>setSelected(selected===w.address?null:w.address)}><span className="pl-rank">{String(i+1).padStart(2,'0')}</span><span className="pl-address">{short(w.address)}<small>{w.count} transfers</small>{(w.rankChange!==null||w.isNew)&&<span className={'pl-move '+(w.isNew||w.rankChange>0?'pl-move-up':w.rankChange<0?'pl-move-down':'pl-move-flat')} title={w.isNew?'No eligible payouts in the prior 30-day ranking':'Rank #'+w.previousRank+' → #'+(i+1)+' over 24 hours'}>{w.isNew?'NEW':w.rankChange>0?'↑'+w.rankChange:w.rankChange<0?'↓'+Math.abs(w.rankChange):'—'} <em>24h</em></span>}</span><strong>{money(w.total)}<small className={'pl-24h'+(w.received24h===0?' pl-24h-zero':'')} title="USDC received in the last 24 hours of this snapshot" aria-label={money(w.received24h)+' USDC received in the last 24 hours'}>+{money(w.received24h)} <span>USDC · 24h</span></small></strong><ChevronDown size={11}/></button>{selected===w.address&&<div className="pl-wallet"><p>{w.address}</p><div className="pl-transfers" tabIndex={0} aria-label="Recipient transfer history">{rows.filter(t=>t.direction==='out'&&t.to.toLowerCase()===w.address).sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp)).map(t=><a key={t.id} href={(t.explorer||config.explorer)+'/tx/'+t.hash} target="_blank" rel="noopener noreferrer"><span>{new Date(t.timestamp).toLocaleDateString(undefined,{month:'short',day:'numeric'})}<small>{t.chain||config.chain}</small></span><b>{money(t.amount)} USDC ↗</b></a>)}</div></div>}</li>)}</ol>:<p className="pl-empty">{!data?'Loading snapshot…':!complete?'A complete 30-day snapshot is not available yet.':'No eligible transfers in this period.'}</p>}<p className="pl-note">Recipient ranking · known internal wallets, bridges and dust excluded. Remaining recipients are not individually verified.{data&&<> <span>As of {new Date(data.updatedAt).toLocaleString()}.</span></>}</p></div>}
 </section>;
}
