import {WEEKLY_FIRMS} from '../../lib/weekly-leaderboard.js';
import {SEASON as WEEK} from '../../lib/season-leaderboard.js';
const usd=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const short=a=>a.slice(0,6)+'…'+a.slice(-4);
export const range=s=>new Date(s).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})+' — '+new Date(s+WEEK).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
export default function WeeklyPoster({board,rows,profiles,firm,person}){
 const list=person?[person]:rows.slice(0,15),h=person?760:395+list.length*66;
 const label=firm==='all'?'ALL FIRMS':WEEKLY_FIRMS.find(f=>f.id===firm)?.name.toUpperCase();
 const houses=person?WEEKLY_FIRMS.filter(f=>person.firms[f.id]):[];
 return <svg xmlns="http://www.w3.org/2000/svg" viewBox={`0 0 1200 ${h}`} role="img" aria-label="GIGAPROP season payout rank card" style={{display:'block',width:'100%',fontFamily:'Manrope,sans-serif'}}>
 <defs><linearGradient id="wk-bg" x2="1" y2="1"><stop stopColor="#353437"/><stop offset=".35" stopColor="#131316"/><stop offset=".75" stopColor="#09090c"/><stop offset="1" stopColor="#272429"/></linearGradient><linearGradient id="wk-metal" x2=".8" y2="1"><stop stopColor="#faf7ed"/><stop offset=".35" stopColor="#aaa5aa"/><stop offset=".55" stopColor="#e9e4dc"/><stop offset="1" stopColor="#625c66"/></linearGradient><linearGradient id="wk-sheen"><stop stopColor="#ffffff00"/><stop offset=".47" stopColor="#ffffff00"/><stop offset=".5" stopColor="#ffffff09"/><stop offset=".6" stopColor="#ffffff00"/></linearGradient><linearGradient id="wk-portrait-fade"><stop stopColor="black"/><stop offset=".5" stopColor="white"/><stop offset=".8" stopColor="white"/><stop offset="1" stopColor="black"/></linearGradient><linearGradient id="wk-portrait-bottom" x2="0" y2="1"><stop stopColor="black"/><stop offset=".2" stopColor="white"/><stop offset=".55" stopColor="white"/><stop offset="1" stopColor="black"/></linearGradient><mask id="wk-portrait-mask" maskContentUnits="objectBoundingBox"><rect width="1" height="1" fill="url(#wk-portrait-fade)"/></mask><mask id="wk-portrait-foot" maskContentUnits="objectBoundingBox"><rect width="1" height="1" fill="url(#wk-portrait-bottom)"/></mask></defs>
 <rect width="1200" height={h} fill="url(#wk-bg)"/><rect x="24" y="24" width="1152" height={h-48} rx="2" fill="none" stroke="#c7bcc341"/><rect width="1200" height={h} fill="url(#wk-sheen)"/>
 <text x="66" y="84" fontSize="42" fontWeight="800" letterSpacing="-3" fill="#e4dfd7">GP.</text><text x="160" y="76" fontFamily="DM Mono,monospace" fontSize="11" letterSpacing="3" fill="#afa5af">GIGAPROP / SEASON SELECT</text><text x="1134" y="76" textAnchor="end" fontFamily="DM Mono,monospace" fontSize="10" letterSpacing="1" fill="#a095a0">{board.closed?'CLOSED EDITION':'LIVE EDITION'} / {label}</text>
 {person?<>
 {profiles[person.address]?.avatar&&<g mask="url(#wk-portrait-foot)"><image href={profiles[person.address].avatar} x="650" y="110" width="510" height="410" preserveAspectRatio="xMidYMid slice" opacity=".50" mask="url(#wk-portrait-mask)"/></g>}
 {houses.map((f,i)=><image key={f.id} href={f.logo} x={710+i*90} y={190+i*50} width="360" height="310" opacity=".065" preserveAspectRatio="xMidYMid meet"/>)}
 <text x="69" y="153" fontFamily="DM Mono,monospace" fontSize="11" letterSpacing="3" fill="#a499a6">A PLACE ON THE RECORD.</text>
 <text x="54" y="375" fontSize={person.rank>99?170:235} fontWeight="800" letterSpacing="-20" fill="url(#wk-metal)">{String(person.rank).padStart(2,'0')}</text>
 <text x="73" y="420" fontFamily="DM Mono,monospace" fontSize="12" letterSpacing="4" fill="#988b9b">SEASON RANK</text>
 {profiles[person.address]?.tag&&<text x="493" y="320" fontSize="15" letterSpacing="3" fill="#d4c1a1">{profiles[person.address].tag}</text>}<text x="490" y="250" fontSize={profiles[person.address]?.username?.length>14?26:34} fontWeight="500" letterSpacing="-1" fill="#ece5e8">{profiles[person.address]?'@'+profiles[person.address].username:short(person.address)}</text>
 <text x="493" y="283" fontFamily="DM Mono,monospace" fontSize="10" letterSpacing="2" fill="#8e8194">{profiles[person.address]?.verifiedAt?'WALLET CONTROL VERIFIED':profiles[person.address]?.editorial?'FEATURED BY GIGAPROP':'UNCLAIMED PAYOUT WALLET'}</text>
 <text x="488" y="385" fontSize="65" letterSpacing="-3" fill="#e6ded5">{usd(person.total)}</text><text x="493" y="418" fontFamily="DM Mono,monospace" fontSize="11" letterSpacing="1" fill="#8f8295">USDC RECEIVED / {person.count} {person.count===1?'PAYOUT':'PAYOUTS'}</text>
 <line x1="70" x2="1130" y1="479" y2="479" stroke="#c0a9c32a"/>
 {houses.map((f,i)=><g key={f.id} transform={`translate(${72+i*240} 515)`}><image href={f.logo} width="26" height="23" preserveAspectRatio="xMidYMid meet"/><text x="38" y="17" fontFamily="DM Mono,monospace" fontSize="12" letterSpacing="1" fill="#b2a2bc">{f.name.toUpperCase()}</text></g>)}
 <text x="72" y="591" fontFamily="DM Mono,monospace" fontSize="12" fill="#8c7d95">{person.address}</text><text x="1132" y="591" textAnchor="end" fontFamily="DM Mono,monospace" fontSize="11" fill="#aa9bb2">{range(board.start)} · UTC</text>
 </>:<>
 <text x="66" y="161" fontSize="62" fontWeight="800" letterSpacing="-3" fill="url(#wk-metal)">THE TOP FIFTEEN.</text><text x="69" y="199" fontFamily="DM Mono,monospace" fontSize="13" fill="#a092ab">{range(board.start)} · UTC</text>
 {list.map((r,i)=><g key={r.address}><rect x="52" y={236+i*66} width="1096" height="60" rx="1" fill={i===0?'#bfb0c314':i%2?'#ffffff03':'transparent'}/><text x="72" y={277+i*66} fontSize="25" fontWeight="500" fill={i<3?'#d8cdd6':'#76677f'}>{String(r.rank).padStart(2,'0')}</text>{profiles[r.address]?.avatar&&<image href={profiles[r.address].avatar} x="130" y={236+i*66} width="360" height="60" preserveAspectRatio="xMidYMid slice" opacity=".27" mask="url(#wk-portrait-mask)"/>}<text x="147" y={276+i*66} fontSize={profiles[r.address]?.username?.length>14?18:24} fontWeight="500" fill="#d2c7d8">{profiles[r.address]?'@'+profiles[r.address].username:short(r.address)}</text><text x="580" y={276+i*66} fontFamily="DM Mono,monospace" fontSize="11" fill="#8e7b99">{Object.keys(r.firms).map(id=>WEEKLY_FIRMS.find(f=>f.id===id)?.name).join(' · ')}</text><text x="1125" y={276+i*66} textAnchor="end" fontSize="26" fill={i<3?'#e2d9d1':'#b8a9c0'}>{usd(r.total)}</text></g>)}
 </>}
 <line x1="66" x2="1134" y1={h-100} y2={h-100} stroke="#b8a5c02d"/><text x="66" y={h-70} fontFamily="DM Mono,monospace" fontSize="10" fill="#8f7a9b">ELIGIBLE USDC RECEIVED · RECIPIENT RANKING, NOT TRADING PNL</text><text x="66" y={h-48} fontFamily="DM Mono,monospace" fontSize="9" fill="#6d587b">As of {new Date(board.asOf).toISOString().replace('T',' ').slice(0,16)} UTC · known internal wallets, bridges and dust excluded.</text><text x="1134" y={h-56} textAnchor="end" fontFamily="DM Mono,monospace" fontSize="12" fill="#bca6c7">gigaprop.xyz/#leaderboard</text>
 </svg>;
}
