import NextMove from '../shared/NextMove';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,ArrowLeft,Download,ShieldCheck,Wallet,Search,X,RefreshCw,ChevronRight,Copy,Check,Trophy} from 'lucide-react';
import {FLOW_SOURCES} from '../../lib/flow-config.js';
import {WEEKLY_FIRMS,rankWeekly,validSnapshot} from '../../lib/weekly-leaderboard.js';
import {seasonDuration,seasonStart as weekStart,seasonKey as weekKey,seasonNumber,validSeasonKey,seasonBoard as weeklyBoard} from '../../lib/season-leaderboard.js';
import {FEATURED_TRADERS} from '../../lib/trader-profiles.js';
import WeeklyPoster,{range} from './WeeklyPoster';
import './weekly.css';
import './frequent-withdrawer.css';

const ROOT='https://raw.githubusercontent.com/deciphe/thepayoutlab/vestflow-data/';
const API='https://gigaprop-profiles.johnhuska1260335.chatgpt.site/api';
const usd=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const short=a=>a.slice(0,6)+'…'+a.slice(-4);
function initial(){const p=new URLSearchParams(window.location.hash.split('?')[1]||'');const w=p.get('season')||p.get('week');return {week:w&&validSeasonKey(w)?w:weekKey(weekStart()),wallet:p.get('wallet'),firm:WEEKLY_FIRMS.some(f=>f.id===p.get('firm'))?p.get('firm'):'all'};}
async function read(path,signal){for(const root of [ROOT,'/data/']){try{const r=await fetch(root+path+'?t='+Math.floor(Date.now()/60000),{signal,cache:'no-store'});if(r.ok)return await r.json();}catch{if(signal?.aborted)throw Error('Cancelled');}}throw Error('Snapshot unavailable');}
async function posterFonts(node){
 const chars=[...new Set(node.textContent)].sort().join('');
 const response=await fetch('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap&text='+encodeURIComponent(chars));
 if(!response.ok)throw Error('Fonts unavailable');
 let css=await response.text();
 const urls=[...new Set([...css.matchAll(/url\(([^)]+)\)/g)].map(m=>m[1].replace(/["']/g,'')))];
 await Promise.all(urls.map(async url=>{const r=await fetch(url);if(!r.ok)throw Error('Font unavailable');const blob=await r.blob();const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)});css=css.split(url).join(data)}));
 return css;
}
function Badges({firms}){return <span className="wk-badges">{WEEKLY_FIRMS.filter(f=>firms[f.id]).map(f=><span key={f.id} title={f.name+' · '+usd(firms[f.id])}><img src={f.logo} alt=""/>{f.name}</span>)}</span>}
function Spark({row,start}){let total=0;const data=[...row.transfers].sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));let line='0,46';for(const t of data){const x=(Date.parse(t.timestamp)-start)/seasonDuration(start)*180;line+=` ${x},${46-total/row.total*40}`;total+=t.amount;line+=` ${x},${46-total/row.total*40}`;}return <svg viewBox="0 0 180 52" aria-hidden="true"><polyline points={line} fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>}
export default function Weekly(){
 const [route]=useState(initial),[week,setWeek]=useState(route.week),[firm,setFirm]=useState(route.firm),[snapshots,setSnapshots]=useState(null),[edition,setEdition]=useState(null),[weeks,setWeeks]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(route.wallet),[profiles,setProfiles]=useState(FEATURED_TRADERS),[profileError,setProfileError]=useState(false),[claim,setClaim]=useState(null),[poster,setPoster]=useState(null),[exporting,setExporting]=useState(false),[copied,setCopied]=useState(false),[history,setHistory]=useState(null);
 const posterRef=useRef(null),dialog=useRef(null),refresh=useRef(()=>{});
 const start=Date.parse(week+'T00:00:00Z'),live=week===weekKey(weekStart());
 useEffect(()=>{const title=document.title;document.title='The Fifteen · GIGAPROP Trader Rankings';return()=>{document.title=title}},[]);
 useEffect(()=>{const c=new AbortController();let running=false;
 async function run(){if(running)return;running=true;setBusy(true);try{const [ds,index]=await Promise.all([Promise.all(FLOW_SOURCES.map(async s=>{const d=await read(s.slug+'.json',AbortSignal.any([c.signal,AbortSignal.timeout(15000)]));if(!validSnapshot(d,s))throw Error('Invalid snapshot');return [s.slug,d]})),read('season-index.json',c.signal).catch(()=>({weeks:[]}))]);if(!c.signal.aborted){setSnapshots(Object.fromEntries(ds));setWeeks((index.weeks||[]).filter(w=>validSeasonKey(w.week)));setError('');}}catch{if(!c.signal.aborted)setError('Live refresh delayed. Showing the last available snapshot.');}finally{running=false;if(!c.signal.aborted)setBusy(false);}}
 refresh.current=run;run();const timer=setInterval(()=>{if(document.visibilityState==='visible')run()},60000);return()=>{c.abort();clearInterval(timer)};
 },[]);
 useEffect(()=>{setEdition(null);const c=new AbortController();read('seasons/'+week+'.json',c.signal).then(d=>{if(d.available&&d.week===week&&!c.signal.aborted)setEdition(d)}).catch(()=>{});return()=>c.abort()},[week]);
 const computed=useMemo(()=>snapshots&&Number.isFinite(start)?weeklyBoard(snapshots,start,Date.now(),edition):null,[snapshots,start,edition]);
 const board=edition?.closed?edition:computed?.available&&(!edition||Date.parse(computed.asOf)>=Date.parse(edition.asOf))?computed:edition;
 const ranked=useMemo(()=>rankWeekly(board,firm),[board,firm]);
 const vestFrequency=useMemo(()=>{
  const rows=rankWeekly(board,'vest').sort((a,b)=>b.count-a.count||b.total-a.total||a.address.localeCompare(b.address));
  return rows.length?{winner:rows[0],ties:rows.filter(r=>r.count===rows[0].count).length}:null;
 },[board]);
 const addresses=ranked.map(r=>r.address).join(',');
 useEffect(()=>{if(!addresses)return;const c=new AbortController(),all=addresses.split(','),chunks=[];for(let i=0;i<all.length;i+=100)chunks.push(all.slice(i,i+100));
 (async()=>{try{const found=[];for(let i=0;i<chunks.length;i+=4){const batch=await Promise.all(chunks.slice(i,i+4).map(async chunk=>{const r=await fetch(API+'/profiles?addresses='+encodeURIComponent(chunk.join(',')),{signal:c.signal});if(!r.ok)throw Error();const d=await r.json();if(!Array.isArray(d.profiles))throw Error();return d.profiles}));found.push(...batch.flat());}if(!c.signal.aborted){setProfiles(p=>({...p,...Object.fromEntries(found.map(x=>[x.address,{...x,...FEATURED_TRADERS[x.address]}]))}));setProfileError(false)}}catch{if(!c.signal.aborted)setProfileError(true)}})();return()=>c.abort()},[addresses]);
 const filtered=query.trim()?ranked.filter(r=>r.address.includes(query.trim().toLowerCase())||profiles[r.address]?.username.includes(query.trim().replace('@','').toLowerCase())).slice(0,15):ranked.slice(0,15);
 const person=ranked.find(r=>r.address===selected),total=ranked.reduce((s,r)=>s+r.total,0),count=ranked.reduce((s,r)=>s+r.count,0),stale=board&&Date.now()-Date.parse(board.asOf)>3600000;
 useEffect(()=>{if((selected||poster||claim)&&dialog.current&&!dialog.current.open)dialog.current.showModal();else if(dialog.current?.open&&!selected&&!poster&&!claim)dialog.current.close()},[selected,poster,claim]);
 function close(){setSelected(null);setPoster(null);setClaim(null);setError('');}
 function linkFor(wallet){return location.origin+location.pathname+'#leaderboard?season='+week+'&firm='+firm+(wallet?'&wallet='+wallet:'');}
 async function copy(wallet){try{await navigator.clipboard.writeText(linkFor(wallet));setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('Could not copy link. You can copy the wallet address below.')}}
 async function download(){if(!posterRef.current)return;setExporting(true);try{const {toBlob}=await import('html-to-image');await document.fonts.ready;const fontEmbedCSS=await posterFonts(posterRef.current);const blob=await toBlob(posterRef.current,{fontEmbedCSS,pixelRatio:3600/posterRef.current.getBoundingClientRect().width,backgroundColor:'#09090b'});if(!blob)throw Error();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gigaprop-season-${week}${poster?.address?'-rank-'+poster.rank:'-top15'}.png`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch{setError('Image download failed. Please try again.')}finally{setExporting(false)}}
 useEffect(()=>{setHistory(null);if(!selected)return;const c=new AbortController();const old=weeks.filter(w=>w.closed&&w.week!==week).slice(0,8);Promise.all(old.map(async w=>{try{const b=await read('seasons/'+w.week+'.json',c.signal),r=rankWeekly(b,firm).find(r=>r.address===selected);return {week:w.week,start:w.start,row:r,available:true}}catch{return {week:w.week,start:w.start,available:false}}})).then(d=>{if(!c.signal.aborted)setHistory(d)});return()=>c.abort()},[selected,weeks,week,firm]);
 const name=r=>profiles[r.address]?'@'+profiles[r.address].username:short(r.address);
 const options=[...new Set([weekKey(weekStart()),...weeks.map(w=>w.week),week])].sort().reverse();
 return <main className="wk"><div className="wk-shell">
 <header className="wk-nav"><a href="#" className="wk-brand">GP.</a><a href="#leaderboard" className="wk-nav-title">TRADER LEAGUE</a><a href="#flow" className="wk-flow-link">Flow trackers <ArrowUpRight size={14}/></a><button onClick={()=>setClaim({address:''})}><Wallet size={14}/> Claim profile</button></header>
 <section className="wk-hero"><div className="wk-eyebrow"><span className="wk-dot"/> {board?.closed?'SEASON RESULTS LOCKED':'RANKED COMPETITION · LIVE'} <span>SEASON {String(seasonNumber(start)).padStart(2,'0')}</span></div><div className="wk-hero-line"><div className="wk-hero-copy"><div className="wk-league-kicker">GIGAPROP / QUARTERLY SEASONS</div><h1>THE TOP<br/><em>FIFTEEN.</em></h1><p>A place on the board. <strong>A name worth knowing.</strong></p><span className="wk-league-note">Ranked by onchain payouts. Earned every season.</span></div><div className="wk-editorial-side"><span className="wk-issue-number">15</span><div className="wk-league-seal"><span>FOUR FIRMS. ONE STANDARD.</span><div className="wk-firm-marks">{WEEKLY_FIRMS.map(f=><img key={f.id} src={f.logo} alt={f.name} title={f.name}/>)}</div><b>SEASON {String(seasonNumber(start)).padStart(2,'0')} / {range(start)}</b></div></div></div>
 <div className="wk-overview"><div><strong>{board?usd(total):'—'}</strong><span>eligible USDC received</span></div><div><strong>{board?ranked.length.toLocaleString():'—'}</strong><span>payout wallets</span></div><div><strong>{board?count.toLocaleString():'—'}</strong><span>individual payouts</span></div><div className="wk-week"><label htmlFor="wk-week">SEASON EDITIONS / UTC</label><select id="wk-week" value={week} onChange={e=>{setWeek(e.target.value);setSelected(null)}}>{options.map(w=><option key={w} value={w}>{range(Date.parse(w+'T00:00:00Z'))}{w===weekKey(weekStart())?' · Live':''}</option>)}</select></div></div></section>
 <div className="wk-controls"><div className="wk-tabs" aria-label="Filter by firm"><button className={firm==='all'?'active':''} onClick={()=>{setFirm('all');setQuery('')}}>All firms</button>{WEEKLY_FIRMS.map(f=><button key={f.id} className={firm===f.id?'active':''} onClick={()=>{setFirm(f.id);setQuery('')}}>{f.name}</button>)}</div><button className="wk-export" disabled={!board||!ranked.length} onClick={()=>setPoster({})}><Download size={14}/> Season image</button></div>
 {error&&<p className="wk-alert" role="status">{error}</p>}
 {stale&&!board?.closed&&<p className="wk-alert">Snapshot delayed · rankings are accurate only through {new Date(board.asOf).toLocaleString()}.</p>}
 {board?<><div className="wk-arena-title"><span>THE PODIUM</span><b>{board.closed?'SEASON FINALISTS':'THE RACE FOR #1'}</b><span>TOP 03</span></div><div className="wk-podium">{ranked.slice(0,3).map((r,i)=><button key={r.address} className={'wk-podium-card wk-place-'+(i+1)+' wk-house-'+Object.keys(r.firms).sort((a,b)=>r.firms[b]-r.firms[a])[0]} onClick={()=>setSelected(r.address)}><div className="wk-podium-top"><span>{i===0?<Trophy size={17}/>:null}{board.closed?['SEASON NO. 1','SECOND PLACE','THIRD PLACE'][i]:['SEASON LEADER','SECOND PLACE','THIRD PLACE'][i]}</span><b>{String(i+1).padStart(2,'0')}</b></div><div className="wk-card-art"><div className="wk-brand-watermarks">{WEEKLY_FIRMS.filter(f=>r.firms[f.id]).map(f=><img key={f.id} src={f.logo} alt=""/>)}</div>{profiles[r.address]?.avatar&&<img className="wk-trader-portrait" src={profiles[r.address].avatar} alt=""/>}<span className="wk-monument-rank">{String(r.rank).padStart(2,'0')}</span><span className="wk-card-edition">GIGAPROP<br/>SEASON SELECT / {week.slice(5)}</span></div><div className="wk-wallet-name">{name(r)}{profiles[r.address]?.verifiedAt&&<ShieldCheck size={15}/>}</div><span className="wk-identity">{profiles[r.address]?.verifiedAt?'Wallet verified':profiles[r.address]?.editorial?'Featured trader':'Unclaimed wallet'}</span>{profiles[r.address]?.tag&&<span className="wk-trader-tag">{profiles[r.address].tag}</span>}<strong className="wk-podium-amount">{usd(r.total)}</strong><Badges firms={r.firms}/><div className="wk-podium-foot"><span>{r.count} {r.count===1?'payout':'payouts'}</span><Spark row={r} start={start}/></div></button>)}</div>

 <div className="wk-table-title"><h2>LEAGUE STANDINGS <span>{firm==='all'?'Combined standings':WEEKLY_FIRMS.find(f=>f.id===firm)?.name}</span></h2><label className="wk-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a wallet or claimed name" aria-label="Search payout wallets"/></label></div>
 <div className="wk-table"><div className="wk-table-head"><span>RANK</span><span>PAYOUT WALLET</span><span>FIRMS</span><span>SEASON PAYOUTS</span><span/></div>{filtered.length?filtered.map(r=><button className="wk-row" key={r.address} onClick={()=>setSelected(r.address)}>{profiles[r.address]?.avatar&&<img className="wk-row-portrait" src={profiles[r.address].avatar} alt=""/>}<span className={'wk-rank '+(r.rank<=3?'wk-top-rank':'')}>{String(r.rank).padStart(2,'0')}</span><span className="wk-row-identity"><strong>{name(r)}{profiles[r.address]?.verifiedAt&&<ShieldCheck size={13}/>}</strong><small>{profiles[r.address]?.tag&&<b className="wk-inline-tag">{profiles[r.address].tag} · </b>}{profiles[r.address]?short(r.address):'Claim this profile'} · {r.count} {r.count===1?'payout':'payouts'}</small></span><Badges firms={r.firms}/><strong className="wk-row-amount">{usd(r.total)}</strong><ChevronRight size={15}/></button>):<div className="wk-empty">{query?'No matching payout wallet in this edition.':'No eligible payouts in this period.'}</div>}</div>
 <div className="wk-asof"><span>{board.closed?'Closed edition':'Live standings'} · {range(start)} · UTC</span><span>Common data cutoff: {new Date(board.asOf).toLocaleString()} <button onClick={()=>refresh.current()} disabled={busy} aria-label="Refresh standings"><RefreshCw size={12}/></button></span></div></>:<div className="wk-empty"><RefreshCw size={20}/><h2>{busy?'Reading the payout record…':'This edition is unavailable'}</h2><p>{busy?'Matching all four firms to the same season window.':computed?.missing?.join(', ')||'A complete snapshot is needed before we can rank this season.'}</p><button onClick={()=>refresh.current()}>Refresh</button></div>}
 <section className="wk-claim-banner"><div className="wk-claim-mark"><ShieldCheck size={24}/></div><div><h2>YOUR RANK. YOUR REPUTATION.<br/><span>Put your name on the board.</span></h2><p>Connect the receiving wallet. Sign a message. Claim your username.</p></div><button onClick={()=>setClaim({address:''})}>Claim your profile <ArrowUpRight size={16}/></button></section>
 <NextMove league/>
 <details className="wk-method"><summary>How the rankings work <span>Transparent rules. Public evidence.</span></summary><div><h3>Money received this season</h3><p>Ranked by eligible USDC sent from our tracked Vest, Breakout, Hypernova and Propr wallets, in calendar-quarter seasons. The extended launch season runs September 1 through December 31, 2026, ending January 1, 2027 at 00:00 UTC (exclusive). From 2027, seasons run January–March, April–June, July–September and October–December. Current standings use the oldest complete source cutoff across all four firms. These are payout-recipient rankings, not trading PnL, ROI or a measure of skill.</p><h3>What is included</h3><p>Known internal firm wallets, identified bridges and transfers below 0.01 USDC are excluded. Refunds, affiliate payments, unidentified treasury transfers and custodial addresses may remain until their purpose is confirmed. Each entry exposes its transaction evidence. Equal totals are ordered by wallet address.</p><h3>Wallets and names</h3><p>One receiving address is one entry, aggregated across supported chains and firms. An address is not necessarily one person; shared or contract addresses can have different controllers. Wallet verified means a signature proved control on the listed chain at the verification time. It does not establish legal identity, firm endorsement or trading-account ownership. Claimed usernames are self-chosen. Featured names and social avatars are editorial mappings supplied by GIGAPROP; they do not receive a wallet-control badge without a signature. Unclaimed wallets remain eligible.</p><h3>Season editions</h3><p>Season records accumulate before source history rolls off. Closed editions preserve the recorded transactions; visible usernames may update as profiles are claimed. Historical editions at launch are reconstructed from available complete history. Rankings cover these four tracked firms only. No paid placement affects rank.</p><a href="mailto:gp@gigaprop.xyz?subject=Season%20leaderboard%20data%20correction">Report a data correction <ArrowUpRight size={13}/></a></div></details>
 {vestFrequency&&(firm==='all'||firm==='vest')&&<button className="wk-frequent" title="Most eligible Vest payout transfers in this season. Equal counts are ordered by total USDC received, then wallet address." onClick={()=>{setFirm('vest');setSelected(vestFrequency.winner.address)}} aria-label={'View '+name(vestFrequency.winner)+', most Vest payouts this season'}>
 <img className="wk-frequent-mark" src="/brands/vest-symbol.svg" alt=""/>
 <span className="wk-frequent-copy"><span className="wk-frequent-kicker">VEST / SIDE QUEST{vestFrequency.ties>1?' / JOINT LEAD':''}</span><strong>Frequent Withdrawer.</strong><span className="wk-frequent-joke">The withdraw button knows them by name.</span></span>
 <span className="wk-frequent-person"><b>{name(vestFrequency.winner)}</b><span>{usd(vestFrequency.winner.total)} received · this season</span></span>
 <span className="wk-frequent-count"><b>{vestFrequency.winner.count.toLocaleString()}</b><span>individual payouts</span></span><ArrowUpRight size={17}/>
 </button>}
 <footer className="wk-footer"><a href="#">GP.</a><span>Public payouts. Independently ranked.</span><a href="#flow">Explore the evidence <ArrowUpRight size={13}/></a></footer>
 <dialog ref={dialog} className="wk-modal" onCancel={close} onClose={close}><button className="wk-close" onClick={close} aria-label="Close"><X size={20}/></button>
 {claim?<ClaimForm initialAddress={claim.address} onClaim={p=>{setProfiles(v=>({...v,[p.address]:{...v[p.address],...p}}));setClaim(null);setSelected(p.address)}}/>:poster&&board?<><div ref={posterRef} className="wk-poster"><WeeklyPoster board={board} rows={ranked} profiles={profiles} firm={firm} person={poster.address?poster:null}/></div><button className="wk-primary" onClick={download} disabled={exporting}><Download size={15}/>{exporting?'Preparing PNG…':'Download 3600px PNG'}</button></>:person?<><div className="wk-profile-label">SEASON RANK / {week}</div>{profiles[person.address]?.avatar&&<img className="wk-profile-portrait" src={profiles[person.address].avatar} alt={profiles[person.address].displayName}/>}<div className="wk-profile-rank">#{String(person.rank).padStart(2,'0')}</div><h2>{name(person)}</h2>{profiles[person.address]?.tag&&<span className="wk-trader-tag">{profiles[person.address].tag}</span>}{profiles[person.address]?.social&&<a className="wk-social" href={profiles[person.address].social} target="_blank" rel="noreferrer">View on X <ArrowUpRight size={12}/></a>}<div className="wk-profile-address">{person.address}</div><p className="wk-verification">{profiles[person.address]?.verifiedAt?<><ShieldCheck size={14}/> Wallet control verified · chain {profiles[person.address].chainId} · {new Date(profiles[person.address].verifiedAt).toLocaleDateString()}</>:profiles[person.address]?.editorial?'Featured by GIGAPROP · wallet supplied by site owner':'Unclaimed wallet · public payout record'}</p><strong className="wk-profile-total">{usd(person.total)}</strong><Badges firms={person.firms}/><div className="wk-profile-actions"><button onClick={()=>{setSelected(null);setPoster(person)}}><Download size={14}/> Rank card</button><button onClick={()=>copy(person.address)}>{copied?<Check size={14}/>:<Copy size={14}/>} Copy profile link</button><button onClick={()=>{setSelected(null);setClaim({address:person.address})}}><Wallet size={14}/>{profiles[person.address]?.verifiedAt?'Manage name':'Claim profile'}</button></div><div className="wk-history"><h3>Previous editions</h3>{history===null?<p>Loading season record…</p>:history.length?history.map(h=><button key={h.week} onClick={()=>setWeek(h.week)}><span>{range(h.start)}</span><b>{!h.available?'Unavailable':h.row?'#'+h.row.rank+' · '+usd(h.row.total):'No eligible payouts'}</b></button>):<p>This is the earliest available edition.</p>}</div><h3 className="wk-evidence-title">Payout evidence <span>{person.count} transfers</span></h3><div className="wk-evidence">{person.transfers.map(t=><a key={t.id} href={t.explorer+'/tx/'+t.hash} target="_blank" rel="noopener noreferrer"><span>{WEEKLY_FIRMS.find(f=>f.id===t.firm)?.name}<small>{new Date(t.timestamp).toLocaleString()} · {t.chain}</small></span><b>{usd(t.amount)}</b><ArrowUpRight size={13}/></a>)}</div></>:selected?<div className="wk-empty">{busy?'Loading wallet…':'This wallet has no eligible payouts in the selected edition or filter.'}</div>:null}
 {profileError&&<p className="wk-alert">Profile names are temporarily unavailable. Wallet rankings are unaffected.</p>}{error&&<p className="wk-alert" role="status">{error}</p>}
 </dialog>
 </div></main>;
}
function ClaimForm({initialAddress,onClaim}){
 const [username,setUsername]=useState(''),[address,setAddress]=useState(initialAddress),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[agree,setAgree]=useState(false);
 async function submit(e){e.preventDefault();if(!agree)return;setBusy(true);setStatus('Connecting wallet…');try{const wallet=window.ethereum;if(!wallet?.request)throw Error('Open this page in your wallet’s browser or install a browser wallet. Exchange deposit addresses cannot sign.');const accounts=await wallet.request({method:'eth_requestAccounts'}),account=accounts[0]?.toLowerCase();if(initialAddress&&account!==initialAddress.toLowerCase())throw Error('Switch to the wallet that received these payouts: '+initialAddress);setAddress(account);const chainId=Number(await wallet.request({method:'eth_chainId'}));if(![1,8453,42161].includes(chainId))throw Error('Switch your wallet network to Ethereum, Base or Arbitrum, then try again.');setStatus('Preparing a one-time signature…');const r=await fetch(API+'/challenge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:account,username:username.toLowerCase(),chainId})});const challenge=await r.json();if(!r.ok)throw Error(challenge.error||'Could not prepare claim.');setStatus('Sign the message in your wallet. No transaction or token approval.');const hex='0x'+Array.from(new TextEncoder().encode(challenge.message),b=>b.toString(16).padStart(2,'0')).join('');const signature=await wallet.request({method:'personal_sign',params:[hex,account]});setStatus('Verifying wallet ownership…');const result=await fetch(API+'/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nonce:challenge.nonce,signature})});const d=await result.json();if(!result.ok)throw Error(d.error||'Could not verify claim.');onClaim(d.profile);}catch(e){setStatus(e.code===4001?'Signature cancelled. Nothing was changed.':e.message||'Could not connect. Please try again.')}finally{setBusy(false)}}
 return <form className="wk-claim-form" onSubmit={submit}><ShieldCheck size={30}/><span className="wk-profile-label">YOUR WALLET. YOUR RECORD.</span><h2>Claim your place.</h2><p>A signature proves you control the payout wallet. Your name appears beside its public payout history.</p>{address&&<div className="wk-profile-address">{address}</div>}<label>Public username<span className="wk-username"><b>@</b><input required minLength={3} maxLength={20} pattern="[a-z0-9_]{3,20}" autoComplete="off" value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} placeholder="yourname"/></span></label><small>3–20 lowercase letters, numbers or underscores.</small><label className="wk-consent"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/>I want this username publicly linked to this wallet and its payout history.</label><button className="wk-primary" disabled={busy||!agree}><Wallet size={15}/>{busy?'Verifying…':'Connect & sign to claim'}</button><p className="wk-claim-note">No payment. No token permissions. Self-custody wallets only; custodial exchange accounts need a separate verification route. A verified wallet is not a verified identity.</p><p role="status" className="wk-claim-status">{status}</p></form>;
}
