import RankCrest from './RankCrest';
import {WEEKLY_FIRMS,WEEK} from '../../lib/weekly-leaderboard.js';
const usd=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const short=a=>a.slice(0,6)+'…'+a.slice(-4);
export const range=s=>new Date(s).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})+' — '+new Date(s+WEEK-1).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
export default function WeeklyPoster({board,rows,profiles,firm,person}){
 const list=person?[person]:rows.slice(0,15),h=person?660:395+list.length*66;
 const label=firm==='all'?'ALL FOUR FIRMS':WEEKLY_FIRMS.find(f=>f.id===firm)?.name.toUpperCase();
 return <svg xmlns="http://www.w3.org/2000/svg" viewBox={`0 0 1200 ${h}`} role="img" aria-label="GIGAPROP weekly payout rank card" style={{display:'block',width:'100%',fontFamily:'Manrope,sans-serif'}}>
 <defs><linearGradient id="wk-bg" x2="1" y2="1"><stop stopColor="#152b49"/><stop offset=".65" stopColor="#080f22"/><stop offset="1" stopColor="#050917"/></linearGradient><linearGradient id="wk-gold"><stop stopColor="#edfbff"/><stop offset="1" stopColor="#64a7ea"/></linearGradient></defs>
 <rect width="1200" height={h} fill="url(#wk-bg)"/><rect x="24" y="24" width="1152" height={h-48} rx="8" fill="none" stroke="#649cdb60"/>
 <text x="66" y="84" fontSize="42" fontWeight="800" letterSpacing="-3" fill="#b9deff">GP.</text><text x="160" y="76" fontFamily="DM Mono,monospace" fontSize="13" letterSpacing="3" fill="#8fafd9">GIGAPROP TRADER LEAGUE</text><text x="1134" y="76" textAnchor="end" fontFamily="DM Mono,monospace" fontSize="12" fill="#8ea5cc">{board.closed?'FINAL EDITION':'LIVE STANDINGS'} / {label}</text>
 <g transform="translate(1000 83) scale(.55)"><RankCrest hero/></g><text x="66" y="160" fontSize="44" fontWeight="800" fontStyle="italic" letterSpacing="-2" fill="url(#wk-gold)">{person?'YOUR RANK. YOUR REPUTATION.':'TRADER LEAGUE / TOP 15'}</text><text x="68" y="198" fontFamily="DM Mono,monospace" fontSize="15" fill="#8b9eba">{range(board.start)} · UTC</text>
 {person?<g><text x="68" y="352" fontSize="126" fontWeight="700" letterSpacing="-8" fill="url(#wk-gold)">#{person.rank.toString().padStart(2,'0')}</text><text x="328" y="297" fontSize="34" fontWeight="600" fill="#e8f3ff">{profiles[person.address]?'@'+profiles[person.address].username:short(person.address)}</text><text x="330" y="335" fontFamily="DM Mono,monospace" fontSize="13" fill="#86a8d3">{profiles[person.address]?'WALLET VERIFIED':'UNCLAIMED PAYOUT WALLET'}</text><text x="328" y="422" fontSize="67" letterSpacing="-3" fill="#c5e6ff">{usd(person.total)}</text><text x="330" y="460" fontFamily="DM Mono,monospace" fontSize="13" fill="#96b2d8">{person.count} PAYOUTS · {Object.keys(person.firms).map(id=>WEEKLY_FIRMS.find(f=>f.id===id)?.name).join(' / ')}</text><text x="68" y="527" fontFamily="DM Mono,monospace" fontSize="16" fill="#87acd9">{person.address}</text></g>:<g>{list.map((r,i)=><g key={r.address}><rect x="52" y={236+i*66} width="1096" height="60" rx="6" fill={i===0?'#508ad32c':i%2?'#ffffff03':'transparent'}/><text x="72" y={277+i*66} fontSize="24" fill={i<3?'#b9deff':'#6d8bae'}>{String(r.rank).padStart(2,'0')}</text><text x="147" y={276+i*66} fontSize="24" fontWeight="500" fill="#d0e5ff">{profiles[r.address]?'@'+profiles[r.address].username:short(r.address)}</text><text x="580" y={276+i*66} fontFamily="DM Mono,monospace" fontSize="12" fill="#7d9ac4">{Object.keys(r.firms).map(id=>WEEKLY_FIRMS.find(f=>f.id===id)?.name).join(' · ')}</text><text x="1125" y={276+i*66} textAnchor="end" fontSize="26" fill={i<3?'#bee7ff':'#a8c7f3'}>{usd(r.total)}</text></g>)}</g>}
 <line x1="66" x2="1134" y1={h-100} y2={h-100} stroke="#6f99ca40"/><text x="66" y={h-70} fontFamily="DM Mono,monospace" fontSize="11" fill="#7f9cc1">ELIGIBLE USDC RECEIVED · RECIPIENT RANKING, NOT TRADING PNL</text><text x="66" y={h-48} fontFamily="DM Mono,monospace" fontSize="10" fill="#6580a4">As of {new Date(board.asOf).toISOString().replace('T',' ').slice(0,16)} UTC · known internal wallets, bridges and dust excluded.</text><text x="1134" y={h-56} textAnchor="end" fontFamily="DM Mono,monospace" fontSize="13" fill="#9ecbff">gigaprop.xyz/#leaderboard</text>
 </svg>;
}
