import assert from 'node:assert/strict';import {weekStart,weeklyBoard,rankWeekly,WEEK} from '../src/lib/weekly-leaderboard.js';import {FLOW_SOURCES} from '../src/lib/flow-config.js';
const start=Date.parse('2026-09-28T00:00:00Z'),end=start+WEEK,recipient='0x1111111111111111111111111111111111111111';
assert.equal(weekStart(start+WEEK-1),start);assert.equal(weekStart(end),end);
const snapshots=Object.fromEntries(FLOW_SOURCES.map(s=>[s.slug,{complete:true,wallet:s.wallet,token:s.token,chain:s.chain,updatedAt:new Date(end).toISOString(),windowEnd:new Date(end).toISOString(),periodStart:new Date(start-86400000).toISOString(),balance:0,transfers:[]}]));
let idx=0;const add=(slug,raw,time,to=recipient)=>{const s=FLOW_SOURCES.find(s=>s.slug===slug);snapshots[slug].transfers.push({id:'tx'+idx,hash:'0x'+String(idx++).padStart(64,'0'),logIndex:1,block:1,timestamp:new Date(time).toISOString(),from:s.wallet,to,direction:'out',raw:String(raw),amount:Number(raw)/1e6})};
add('vestflow',1000000,start);add('breakoutflow',2000000,start+1);add('vestflow',9000000,end);add('vestflow',9999,start+1);add('vestflow',8000000,start+1,FLOW_SOURCES.find(s=>s.slug==='novaflow').wallet);snapshots.vestflow.transfers.push({...snapshots.vestflow.transfers[0]});
let board=weeklyBoard(snapshots,start,end);assert(board.available&&board.closed);assert.equal(board.transfers.length,2);let ranks=rankWeekly(board);assert.equal(ranks.length,1);assert.equal(ranks[0].total,3);assert.equal(rankWeekly(board,'vest')[0].total,1);assert.equal(rankWeekly(board,'breakout')[0].total,2);
snapshots.proprflow.windowEnd=new Date(start).toISOString();board=weeklyBoard(snapshots,start,end);assert.equal(board.closed,false);assert.equal(board.transfers.length,1);snapshots.proprflow.complete=false;assert.equal(weeklyBoard(snapshots,start,end).available,false);
console.log('Weekly boundaries, integer totals, cross-firm aggregation, deduplication, treasury/dust exclusions, firm filters and common cutoff passed.');
