import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {build} from 'vite';
import {executionMetrics as metrics} from '../src/components/web3/executionMetrics.js';
const vest=metrics(.0025,50), vanta=metrics(0,2.5);
assert.equal(vest.feeDrag,.25);
assert.ok(Math.abs(vest.requiredMove-.205)<1e-12);
assert.equal(vanta.requiredMove,4);
assert.ok(vest.reach>vanta.reach);
assert.ok(Math.abs(vanta.requiredMove/vest.requiredMove-19.51219512195122)<1e-10);
assert.equal(metrics(0,50).requiredMove,.2);
assert.equal(metrics(.005,10).requiredMove,1.01);
assert.ok(metrics(.05,10).requiredMove>metrics(.005,10).requiredMove);
assert.ok(metrics(.005,50).requiredMove<metrics(.005,10).requiredMove);
for(const args of [[null,10],[.01,null],[.01,0],[-1,10],[.0025,50,0]]) assert.equal(metrics(...args).reach,null);
// Rendering the actual app catches undefined JSX components that Vite compilation misses.
const result=await build({configFile:false,esbuild:{jsx:"automatic"},ssr:{noExternal:['lucide-react']},logLevel:'error',build:{ssr:'src/App.jsx',write:false,minify:false,rollupOptions:{output:{format:'cjs'}}}});
const require=createRequire(import.meta.url);
const output=Array.isArray(result)?result[0]:result;
const chunk=output.output.find(x=>x.type==='chunk'&&x.isEntry);
const mod={exports:{}};
new Function('require','module','exports',chunk.code)(require,mod,mod.exports);
const React=require('react');
const {renderToString}=require('react-dom/server');
const html=renderToString(React.createElement(mod.exports.default || mod.exports));
for(const text of ['Firm deck','True R velocity','Vest','Hypernova','Breakout','Vanta','Propr']) assert.ok(html.includes(text),text);
assert.ok(!html.includes('Open Doji'));
assert.ok(!html.includes('Open HyperPNL'));
assert.ok(html.includes('0.205%'));
assert.ok(html.includes('Taker fees'));
for (const extra of ['>EURUSD<','>CL<','>maker<','>avg<']) assert.ok(!html.includes(extra));
console.log('Web3 render and fee/leverage checks passed.');
