import React,{useRef,useState} from 'react';
import CardWheel from './CardWheel';
import WispMark from './WispMark';
import {certificates, orderedCertificates} from './data';
import {depositById, depositCount} from './deposits';
const ordered=orderedCertificates.map(c=>({...c,deposit:depositById[c.id]}));
const money=n=>'$'+n.toLocaleString('en-US');
const recordCount=certificates.length;
const totalValue=certificates.reduce((sum,c)=>sum+c.amountNum,0);
const largestValue=Math.max(...certificates.map(c=>c.amountNum));
export default function App(){const dialog=useRef(null);const[active,setActive]=useState(null);function open(c=null){setActive(c);dialog.current.showModal()}
return <main className="maven-edition"><header className="mv-nav"><a href="../"><WispMark size={32}/>the payout lab<span>.</span></a><nav><a href="#proof">The proof</a><a href="#trust">Why Maven</a><a href="../">Payout Lab ↗</a></nav></header>
<section className="mv-hero" id="hero"><div className="mv-hero-copy"><div className="mv-eyebrow">THE PAYOUT LAB / MAVEN EDITION</div><h1>TRUST.<br/>WITH <span>RECEIPTS.</span></h1><p>One firm. My own history.<br/>Every Maven payout in one place.</p><div className="mv-actions"><button onClick={()=>open()}>See my Maven payouts ↗</button><a href="#trust">Why I trust Maven ↓</a></div><div className="mv-small-proof"><i/>Never denied. Never delayed. My Maven experience.</div></div><CardWheel/></section>
<div className="mv-stats"><div><strong>{recordCount}</strong><span>Maven certificates</span></div><div><strong>{depositCount}</strong><span>Matched USDC deposits</span></div><div><strong>{money(totalValue)}</strong><span>Total certificate value*</span></div><div><strong>{money(largestValue)}</strong><span>Largest certificate</span></div></div><p className="mv-stat-note">*Some historical certificates show pre-split amounts. Deposit receipts show the corresponding USDC arrival where a matching record was available. Certificate value is not net profit or total cash received.</p>
<section className="mv-vault" id="proof"><div><div className="mv-eyebrow">01 / CERTIFICATE + DEPOSIT</div><h2>Two sides of the same payout.</h2><p>{recordCount} certificates · {depositCount} matched USDC deposits</p></div><div className="mv-fan" aria-hidden="true">{ordered.slice(0,10).map((c,i)=><img key={c.id} src={c.url} alt="" style={{left:i*88,transform:`rotate(${Math.min(i,5)*1.1-2}deg)`,zIndex:10-i,filter:`blur(${Math.max(0,i-1)*1.6}px)`,opacity:Math.max(.1,1-i*.12)}}/>)}</div><button onClick={()=>open()}>Open paired archive ↗</button></section>
<section className="mv-trust" id="trust"><div><div className="mv-eyebrow">02 / TRUST IS PERSONAL</div><h2>I don't need<br/>to borrow <span>proof.</span></h2><p>These are my Maven payout records. They're why Maven has earned my trust—and why I'm putting the evidence first.</p><img className="mv-wisp" src={`${import.meta.env.BASE_URL}mascot/wisp.png`} alt="Wisp peeking over the edge"/></div><div className="mv-principles"><article><span>01</span><div><h3>A history, not a headline.</h3><p>31 records across more than two years. Open the archive and inspect the amounts and dates yourself.</p></div></article><article><span>02</span><div><h3>No denials in my experience.</h3><p>I've never had a payout denied. That's my personal track record, not a promise about anyone else's next request.</p></div></article><article><span>03</span><div><h3>The receipt stays intact.</h3><p>Original certificates, not recreated claims. Historical splits explain why a certificate amount can differ from the deposit.</p></div></article></div></section>
<section className="mv-paradox" id="paradox"><div className="mv-paradox-intro"><div className="mv-eyebrow">03 / THE MAVEN PARADOX</div><h2>The best part?<br/><span>No payout drama.</span></h2><p>A bigger number means little if I can't trust the journey. With Maven, my confidence comes from being paid—not just being promised.</p></div><div className="mv-paradox-results"><div><small>DENIED PAYOUTS</small><strong>Never.</strong></div><div><small>DELAYED PAYOUTS</small><strong>Never.</strong></div><div><small>MY ARCHIVE</small><strong>31 records.</strong></div></div><div className="mv-paradox-foot"><span>MY PERSONAL TRACK RECORD</span><button onClick={()=>open()}>Open the evidence ↗</button></div></section>
<section className="mv-lesson"><div><div className="mv-eyebrow">04 / TRUE R / TRUST IN THE JOURNEY</div><h2>Trust compounds.<br/><span>One receipt at a time.</span></h2><p>My True R lens looks beyond the headline amount: the costs, the rules, the time—and my confidence in getting paid.</p></div><div className="mv-trust-path"><div><i>01</i><h3>The terms.</h3><p>Understand the account and payout requirements.</p></div><div><i>02</i><h3>The experience.</h3><p>No denial or delay in my own Maven history.</p></div><div><i>03</i><h3>The evidence.</h3><p>{recordCount} certificates. {money(totalValue)} in stated value.</p></div></div><p className="mv-lesson-note">“Never” describes my experience, not an unconditional payout guarantee. Product schedules and eligibility still apply.</p></section>
<section className="mv-close"><div className="mv-eyebrow">05 / THE FIRM BEHIND THE RECEIPTS</div><h2>Maven. Through<br/><span>my own experience.</span></h2><p>Proof first. Then your decision.</p><div className="mv-actions"><button onClick={()=>open()}>Explore my payout history ↗</button><a href="https://maventrading.com" target="_blank" rel="noopener noreferrer">Explore Maven ↗</a></div><small>Check current account terms and eligibility directly with Maven.</small></section>
<footer className="mv-footer"><a href="#hero">THE PAYOUT LAB<span> / MAVEN EDITION</span></a><p>Independent personal experience. Not an official Maven site.<br/>Payout history does not guarantee future results.</p></footer>
<dialog className="mv-dialog" ref={dialog}><header><span>{active?'Maven / '+active.amount:`Maven proof archive / ${recordCount} certificates · ${depositCount} deposits`}</span><button onClick={()=>dialog.current.close()} aria-label="Close payout archive">Close ✕</button></header>{active?<div className="mv-single"><button onClick={()=>setActive(null)}>← All records</button><div className="mv-proof-pair"><figure><figcaption>01 / PAYOUT CERTIFICATE</figcaption><img className="mv-pair-cert" src={active.url} alt={`Maven certificate ${active.amount}, ${active.date}`}/></figure><figure className={!active.deposit?'is-missing':''}><figcaption>02 / USDC DEPOSIT</figcaption>{active.deposit?<img className="mv-pair-deposit" src={active.deposit} alt={`USDC deposit corresponding to Maven certificate ${active.amount}`}/>:<p>Matching deposit image not available in the supplied archive.</p>}</figure></div><p>{active.amount} · {active.date} · Certificate and deposit evidence</p></div>:<div className="mv-grid">{ordered.map(c=><button className="mv-proof-card" key={c.id} onClick={()=>setActive(c)}><img className="mv-grid-cert" src={c.url} alt={`Maven certificate ${c.amount}`} loading="lazy"/>{c.deposit?<img className="mv-grid-deposit" src={c.deposit} alt="Matched USDC deposit" loading="lazy"/>:<div className="mv-grid-missing">Certificate only</div>}<span>{c.amount}<small>{c.date}</small></span></button>)}</div>}</dialog></main>}
