import React,{useRef,useState} from 'react';
import CardWheel from './CardWheel';
import WispMark from './WispMark';
import {certificates, orderedCertificates} from './data';
import {depositById, depositCount} from './deposits';
const ordered=orderedCertificates.map(c=>({...c,deposit:depositById[c.id]}));
const money=n=>'$'+n.toLocaleString('en-US');
const recordCount=certificates.length;
const totalValue=certificates.reduce((sum,c)=>sum+c.amountNum,0);
const largestValue=Math.max(...certificates.map(c=>c.amountNum));
export default function App(){const dialog=useRef(null);const[active,setActive]=useState(null);function open(c=null){setActive(c);dialog.current.showModal()}
return <main className="maven-edition"><header className="mv-nav"><a href="../"><WispMark size={32}/>gigaprop<span>.</span></a><nav><a href="#proof">Proof</a><a href="#pick">My pick</a><a href="../">gigaprop ↗</a></nav></header>
<section className="mv-hero" id="hero"><div className="mv-hero-copy"><div className="mv-eyebrow">MAVEN EDITION</div><h1>TRUST.<br/>WITH <span>RECEIPTS.</span></h1><div className="mv-hero-promise"><p>My most proven firm.</p><strong><span>Never denied.</span> <span>Never delayed.</span></strong></div><div className="mv-actions"><button onClick={()=>open()}>See my Maven payouts ↗</button><a href="#pick">My pick ↓</a></div></div><CardWheel/></section>
<div className="mv-stats"><div><strong>{recordCount}</strong><span>Certificates</span></div><div><strong>{depositCount}</strong><span>Matched deposits</span></div><div><strong>{money(totalValue)}</strong><span>Recorded value*</span></div><div><strong>{money(largestValue)}</strong><span>Largest certificate</span></div></div><p className="mv-stat-note">*Historical certificates can show pre-split amounts. Matched deposit receipts show cash arrival where available.</p>
<section className="mv-vault" id="proof"><div><h2>Certificate + deposit.</h2><p>{recordCount} certificates · {depositCount} matched USDC deposits</p></div><div className="mv-fan" aria-hidden="true">{ordered.slice(0,10).map((c,i)=><img key={c.id} src={c.url} alt="" style={{left:i*88,transform:`rotate(${Math.min(i,5)*1.1-2}deg)`,zIndex:10-i,filter:`blur(${Math.max(0,i-1)*1.6}px)`,opacity:Math.max(.1,1-i*.12)}}/>)}</div><button onClick={()=>open()}>Open paired archive ↗</button></section>
<section className="mv-trust" id="trust"><div><h2>Why Maven.</h2><p>The relationship is simple: they kept paying me, so they earned the top spot.</p><img className="mv-wisp" src={`${import.meta.env.BASE_URL}mascot/wisp.png`} alt="Wisp peeking over the edge"/></div><div className="mv-principles"><article><span>01</span><div><h3>Deepest history.</h3><p>{recordCount} payout certificates across my Maven record.</p></div></article><article><span>02</span><div><h3>No denial in my experience.</h3><p>My requests were paid. That is my track record, not a guarantee about anyone else's.</p></div></article><article><span>03</span><div><h3>Cash-side proof.</h3><p>Where available, the certificate is paired with its matching USDC deposit.</p></div></article></div></section>
<section className="mv-paradox" id="pick"><div className="mv-paradox-intro"><div className="mv-eyebrow">MY PICK</div><h2>100K<br/><span>OMO 2-Step.</span></h2><p>Roomy drawdown, no consistency score, and the firm I have the most reason to trust from my own payouts.</p></div><div className="mv-paradox-results"><div><small>PROFIT TARGET</small><strong>6% / 8%</strong></div><div><small>MAX LOSS</small><strong>8%</strong></div><div><small>CONSISTENCY</small><strong>None.</strong></div></div><div className="mv-paradox-foot"><span>4% daily loss · 80% split · 10 business-day payout schedule</span><a href="https://maventrading.com" target="_blank" rel="noopener noreferrer">View Maven ↗</a></div></section>
<footer className="mv-footer"><a href="#hero">gigaprop<span> / maven edition</span></a><p>Independent personal experience. Not an official Maven site.<br/>Terms change. Check Maven before purchasing.</p></footer>
<dialog className="mv-dialog" ref={dialog}><header><span>{active?'Maven proof':`Maven proof archive / ${recordCount} certificates · ${depositCount} deposits`}</span><button onClick={()=>dialog.current.close()} aria-label="Close payout archive">Close ✕</button></header>{active?<div className="mv-single"><button onClick={()=>setActive(null)}>← All records</button><div className="mv-proof-pair"><figure><figcaption>PAYOUT CERTIFICATE</figcaption><img className="mv-pair-cert" src={active.url} alt={`Maven certificate ${active.amount}, ${active.date}`}/></figure><figure className={!active.deposit?'is-missing':''}><figcaption>USDC DEPOSIT</figcaption>{active.deposit?<img className="mv-pair-deposit" src={active.deposit} alt={`USDC deposit corresponding to Maven certificate ${active.amount}`}/>:<p>Matching deposit image not available in the supplied archive.</p>}</figure></div><p>{active.date}</p></div>:<div className="mv-grid">{ordered.map(c=><button className="mv-proof-card" key={c.id} onClick={()=>setActive(c)}><img className="mv-grid-cert" src={c.url} alt={`Maven certificate ${c.amount}`} loading="lazy"/>{c.deposit?<img className="mv-grid-deposit" src={c.deposit} alt="Matched USDC deposit" loading="lazy"/>:<div className="mv-grid-missing">Certificate only</div>}<span><small>{c.date}</small></span></button>)}</div>}</dialog></main>}
